/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("amr.belajar.kotlin.coroutine.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
}

application {
    // Define the main class for the application.
    mainClass.set("amr.belajar.kotlin.coroutine.app.AppKt")
}
